image: Visual Studio 2017

platform:
  - x64

environment:
  matrix:
    - nodejs_version: 10

cache:
  - '%LOCALAPPDATA%/Yarn'
  - node_modules
  - '%USERPROFILE%\.electron'

matrix:
  fast_finish: true

build: off

version: '{build}'

shallow_clone: true

clone_depth: 1

skip_branch_with_pr: true

install:
  - ps: Install-Product node $env:nodejs_version x64
  - set CI=true
  - yarn

test_script:
  - yarn package-ci
  - yarn lint
  - yarn lint-styles
  - yarn tsc
  - yarn test
  # - yarn coveralls
  # - yarn build-e2e
  # - yarn test-e2e
