name: CI

on: [push]

jobs:
  test:
    name: Run tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node_version: [10.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: set git config
        run: |
          git config --global core.eol lf
          git config --global core.autocrlf false
      - name: ubuntu file watcher tweak
        if: matrix.os == 'ubuntu-latest'
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      - uses: actions/checkout@v1
      - name: setup nodejs
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: install yarn
        run: npm install -g yarn
      - name: install dependencies
        run: yarn
      - name: lint code
        run: yarn lint
      - name: lint styles
        run: yarn lint:styles
      - name: typescript compile
        run: yarn tsc
      - name: unit tests
        run: yarn test
        env:
          CI: true
      - name: coverage
        run: yarn test:codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: e2e tests (mac & windows)
        if: matrix.os != 'ubuntu-latest'
        run: yarn test:e2e
